# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-08 17:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('perfil_usuario', models.IntegerField(choices=[(0, 'Profesor'), (1, 'Estudiante')], default=0, verbose_name='Tipo de documento')),
                ('imagen_perfil', models.ImageField(null=True, upload_to='imagenes_perfil/', verbose_name='Imagen de perfil')),
            ],
            options={
                'verbose_name': 'user',
                'abstract': False,
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
