# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-08 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='perfil_usuario',
            field=models.IntegerField(choices=[(0, 'Profesor'), (1, 'Estudiante')], default=0, verbose_name='Perfil de usuario'),
        ),
    ]
