# Generated by Django 2.1.1 on 2018-11-21 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('respuesta', models.BooleanField(choices=[(0, True), (1, False)], verbose_name='Respuesta correcta')),
                ('tipo', models.CharField(default='Pregunta de Falso o Verdadero', max_length=70)),
                ('imagen_pregunta', models.ImageField(null=True, upload_to='imagenes_preguntas/', verbose_name='Imagen de pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Unica_respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
            ],
        ),
    ]
