# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-09 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=300, verbose_name='Pregunta')),
                ('respuesta', models.BooleanField(choices=[(0, True), (1, False)], verbose_name='Respuesta correcta')),
                ('tipo', models.CharField(default='Pregunta de Falso o Verdadero', max_length=70)),
            ],
        ),
    ]
